import type { Metadata } from 'next';
import { IBM_Plex_Sans, Geist } from 'next/font/google';
import './globals.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';
import { cn } from "@/lib/utils";
import SplashCursor from '@/components/SplashCursor';

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const ibmPlexSans = IBM_Plex_Sans({
	variable: '--font-ibm-plex-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'MushaNexa',
	description: 'Generated by create next app',
	icons: {
		icon: './favicon.png',
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className={cn("antialiased", ibmPlexSans.variable, "font-sans", geist.variable)}>
			<body className='select-none overflow-x-hidden'>
				<Navbar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
